version: '3.8'

services:
  amedia-postgres-service:
    container_name: amedia-postgresql
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: postgres_userz
      POSTGRES_PASSWORD: pass123z
      POSTGRES_DB: local-database
      CORS_ALLOWED_ORIGIN: "http://localhost:3000"
    ports:
      - "5432:5432"
    volumes:
      - local-postgres-volume:/var/lib/postgresql/data

  app:
    image: amedia-skotn-backend:latest
    #build: .
    depends_on:
      - amedia-postgres-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://amedia-postgres-service:5432/local-database
      SPRING_DATASOURCE_USERNAME: postgres_userz
      SPRING_DATASOURCE_PASSWORD: pass123z
    ports:
      - "8080:8080"

  frontend:
    image: amedia-skotn-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - app

volumes:
  local-postgres-volume: